apiVersion: batch/v1
kind: CronJob
metadata:
  name: cantonmonitor-agent
  namespace: validator
spec:
  schedule: "* * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          securityContext:
            runAsNonRoot: true
            runAsUser: 10001
            runAsGroup: 10001
          containers:
            - name: cantonmonitor-agent
              image: ghcr.io/crypt0jan/cantonmonitor-agent:latest
              imagePullPolicy: IfNotPresent

              # Environment variables
              env:
                # Secrets (must exist in this namespace)
                - name: KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: cantonmonitor-secrets
                      key: CM_VALIDATOR_ID
                - name: SECRET
                  valueFrom:
                    secretKeyRef:
                      name: cantonmonitor-secrets
                      key: CM_SECRET

                # Optional overrides
                - name: BACKEND_BASE
                  value: "https://api.cantonmonitor.com"
                - name: VERSION_URI
                  value: "http://validator-app:5003/api/validator/version"
                - name: TIMEOUT
                  value: "6"
                - name: INSECURE
                  value: "0"
                - name: POST_PATH
                  value: "/health"

              # Lightweight resource footprint
              resources:
                requests:
                  cpu: "10m"
                  memory: "32Mi"
                limits:
                  cpu: "100m"
                  memory: "128Mi"

              # Execute the embedded cantonmonitor.sh once per job run
              command: ["/bin/sh", "-c"]
              args:
                - |
                  set -euo pipefail
                  /app/cantonmonitor.sh